### ISSUE TITLE
Error: Email Required

### ISSUE THREAD

**Issue by kerbyj** [rsrdesarrollo/generator-burp-extension#3]
Hey, I wanted to try this tool, but for some reason it crashes after license choising. I tried to figure it out, but my knowledge of node js is not enough

**Trace:**
```
? What's your name: dd
? Your email (optional): 
? Your website (optional): 
? Which license do you want to use? Apache 2.0
Error: Email required
    at module.exports (/usr/local/lib/node_modules/generator-burp-extension/node_modules/github-username/index.js:30:25)
    at Object.user.github.username (/usr/local/lib/node_modules/generator-burp-extension/node_modules/yeoman-generator/lib/actions/user.js:62:30)
    at /usr/local/lib/node_modules/yo/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/yo/node_modules/run-async/index.js:26:19
    at Object.exports.fetchAsyncQuestionProperty (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/utils/utils.js:23:29)
    at MergeMapSubscriber.obs.pipe.concatMap [as project] (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/ui/prompt.js:88:17)
    at MergeMapSubscriber._tryNext (/usr/local/lib/node_modules/yo/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/usr/local/lib/node_modules/yo/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/usr/local/lib/node_modules/yo/node_modules/rxjs/internal/Subscriber.js:66:18)
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Email required
    at module.exports (/usr/local/lib/node_modules/generator-burp-extension/node_modules/github-username/index.js:30:25)
    at Object.user.github.username (/usr/local/lib/node_modules/generator-burp-extension/node_modules/yeoman-generator/lib/actions/user.js:62:30)
    at /usr/local/lib/node_modules/yo/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/yo/node_modules/run-async/index.js:26:19
    at Object.exports.fetchAsyncQuestionProperty (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/utils/utils.js:23:29)
    at MergeMapSubscriber.obs.pipe.concatMap [as project] (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/ui/prompt.js:88:17)
    at MergeMapSubscriber._tryNext (/usr/local/lib/node_modules/yo/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/usr/local/lib/node_modules/yo/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/usr/local/lib/node_modules/yo/node_modules/rxjs/internal/Subscriber.js:66:18)
Emitted 'error' event at:
    at Immediate.setImmediate (/usr/local/lib/node_modules/generator-burp-extension/node_modules/yeoman-generator/lib/index.js:406:18)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)

```

**Specs:**
OS: `Linux Mint 20 x86_64`
Node: `v10.19.0`
NPM: `6.14.7`

**Comment by rsrdesarrollo** [comment]
@kerbyj 

It's an issue related with https://github.com/yeoman/generator-generator/issues/166

looks like email is not optional at the end 😅 

For a valid workaround, you should set correctly the email address in your git global config as shown:

`git config --global user.email <email>`

being email your email at github

**Comment by rsrdesarrollo** [comment]
I also fixed an issue related with a missing gitignore file, so you will have to reinstall generator once is uploaded to NPM

https://github.com/rsrdesarrollo/generator-burp-extension/commit/71063482700a014e3794a502798369273fc01b03

**Comment by kerbyj** [comment]
I didn't think there would be such a simple solution. Thank you so much 👍
