### ISSUE TITLE
Error email required

### ISSUE THREAD

**Issue by chrisgds** [rsrdesarrollo/generator-burp-extension#4]
keep getting the following error when running the generator:

```
? What's your name: test
? Your email (optional): test@test.com
? Your website (optional):
? Which license do you want to use? Apache 2.0

     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

Error: Email required
    at module.exports (/usr/local/lib/node_modules/generator-burp-extension/node_modules/github-username/index.js:6:9)
    at Object.user.github.username (/usr/local/lib/node_modules/generator-burp-extension/node_modules/yeoman-generator/lib/actions/user.js:62:30)
    at /usr/local/lib/node_modules/yo/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/yo/node_modules/run-async/index.js:26:19
    at Object.exports.fetchAsyncQuestionProperty (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/utils/utils.js:23:29)
    at MergeMapSubscriber.project (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/ui/prompt.js:88:17)
    at MergeMapSubscriber._tryNext (/usr/local/lib/node_modules/yo/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/usr/local/lib/node_modules/yo/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/usr/local/lib/node_modules/yo/node_modules/rxjs/internal/Subscriber.js:66:18)
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: Email required
    at module.exports (/usr/local/lib/node_modules/generator-burp-extension/node_modules/github-username/index.js:6:9)
    at Object.user.github.username (/usr/local/lib/node_modules/generator-burp-extension/node_modules/yeoman-generator/lib/actions/user.js:62:30)
    at /usr/local/lib/node_modules/yo/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/yo/node_modules/run-async/index.js:26:19
    at Object.exports.fetchAsyncQuestionProperty (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/utils/utils.js:23:29)
    at MergeMapSubscriber.project (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/ui/prompt.js:88:17)
    at MergeMapSubscriber._tryNext (/usr/local/lib/node_modules/yo/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/usr/local/lib/node_modules/yo/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/usr/local/lib/node_modules/yo/node_modules/rxjs/internal/Subscriber.js:66:18)
Emitted 'error' event on  instance at:
    at Immediate.<anonymous> (/usr/local/lib/node_modules/generator-burp-extension/node_modules/yeoman-generator/lib/index.js:1022:20)
    at processImmediate (internal/timers.js:461:21)
```

**Comment by rsrdesarrollo** [comment]
Duplicated of #3 

Please read the workarround https://github.com/rsrdesarrollo/generator-burp-extension/issues/3#issuecomment-676269422
